version: '3'

services:
  aptly-mirror:
    image: coralhl/aptly
    container_name: aptly-mirror
    restart: always
    # environment:
    #   - GPG_PASSPHRASE=super-secret-passphrase
    #   - MIRR_FILE=/opt/aptly/mirrors.yml
    #   - LOG_FILE=/var/log/aptly/aptly.log
    ports:
      - 80:80
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /opt/docker/aptly/data:/opt/aptly
      - /opt/docker/aptly/log:/var/log/aptly
