version: '3'

services:
  aptly-mirror:
    image: coralhl/aptly
    container_name: aptly-mirror
    restart: always
    # environment:
    #   - GPG_PASSPHRASE="super-secret-passphrase" 
    networks:
      - proxy_default
    ports:
      - 80:80
    volumes:
      - /opt/docker/aptly:/opt/aptly